FROM bernddoser/docker-devel-cpp:cuda-8.0-devel-cmake-3.9.1-gtest-1.8.0-doxygen-1.8.13

MAINTAINER Bernd Doser <bernd.doser@h-its.org>

RUN apt-get update \
 && apt-get install -y \
    libboost-all-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
