[project]
name = "astro-pink"
version = "2.5"

[build-system]
requires = [
    "cmake>=3.9",
    "conan==1.*",
    "ninja",
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["python"]
include = ["pink*"]
namespaces = false
