FROM braintwister/ubuntu-18.04-cmake-3.14-gcc-8-conan-1.16

LABEL maintainer="Bernd Doser <bernd.doser@h-its.org>"

ENV TZ 'Europe/Berlin'
ENV DEBIAN_FRONTEND noninteractive

RUN echo $TZ > /etc/timezone && \
  apt-get update && apt-get install -y tzdata && \
  rm /etc/localtime && \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
  dpkg-reconfigure -f noninteractive tzdata && \
  apt-get clean

RUN apt-get update && apt-get install -y --no-install-recommends \
        python3-tk \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && \
    hash -r pip3 && \
    pip3 install -I \
    jupyter \
    matplotlib \
    numpy \
    tensorflow \
    tqdm

RUN git clone https://github.com/HITS-AIN/PINK.git && \
    cd PINK && \
    git checkout 2.3 && \
    mkdir build && cd build && \
    cmake .. && \
    make

ENV PYTHONPATH /PINK/build/lib
ENV JUPYTER_PATH /PINK/build/lib

COPY notebooks-cpu /notebooks

# Add entrypoint
ADD chmod_notebooks.sh /entrypoint.d/

# Set up notebook config
COPY jupyter_notebook_config.py /jupyter-config/
ENV JUPYTER_CONFIG_DIR /jupyter-config

WORKDIR /notebooks
EXPOSE 8888

CMD ["bash", "-c", "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/notebooks --ip 0.0.0.0 --no-browser --allow-root"]
