FROM braintwister/ubuntu-18.04-cmake-3.15-gcc-8-conan-1.19

LABEL maintainer="Bernd Doser <bernd.doser@h-its.org>"

ENV TZ 'Europe/Berlin'
ENV DEBIAN_FRONTEND noninteractive

RUN echo $TZ > /etc/timezone && \
  apt-get update && apt-get install -y tzdata && \
  rm /etc/localtime && \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
  dpkg-reconfigure -f noninteractive tzdata && \
  apt-get clean

RUN apt-get update && apt-get install -y --no-install-recommends \
        libomp-dev \
        libsm6 \
        libxext6 \
        libxrender-dev \
        python3-tk \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && \
    hash -r pip3 && \
    pip3 install -I \
    googledrivedownloader \
    jupyter \
    matplotlib \
    numpy \
    opencv-python \
    tensorflow \
    tqdm

RUN git clone https://github.com/HITS-AIN/PINK.git && \
    cd PINK && \
    git checkout 2.4-rc3 && \
    mkdir build && cd build && \
    cmake .. && \
    make

ENV PYTHONPATH /PINK/build/lib:/PINK/scripts
ENV JUPYTER_PATH /PINK/build/lib:/PINK/scripts

# Add entrypoint
RUN cp /PINK/jupyter/chmod_notebooks.sh /entrypoint.d

# Set up notebook config
RUN mkdir /jupyter-config/ && \
    cp /PINK/jupyter/jupyter_notebook_config.py /jupyter-config/
ENV JUPYTER_CONFIG_DIR /jupyter-config

RUN cp -r /PINK/jupyter/notebooks /

WORKDIR /notebooks
EXPOSE 8888

CMD ["bash", "-c", "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/notebooks --ip 0.0.0.0 --no-browser --allow-root"]
