FROM nvidia/cuda:9.2-devel-ubuntu18.04

LABEL maintainer="Bernd Doser <bernd.doser@h-its.org>"

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        python3 \
        python3-dev \
        python3-pip \
        python3-setuptools \
        #python3-tk \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && \
    hash -r pip3 && \
    pip3 install -I \
    conan \
    jupyter \
    matplotlib \
    numpy \
    tensorflow \
    tqdm

ENV PYTHONPATH /PINK/build/lib
ENV JUPYTER_PATH /PINK/build/lib

WORKDIR /notebooks
EXPOSE 8888

CMD ["bash", "-c", "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/notebooks --ip 0.0.0.0 --no-browser --allow-root"]
