FROM braintwister/ubuntu-18.04-cuda-10.1-cmake-3.15-gcc-7-conan-1.18

MAINTAINER Bernd Doser <bernd.doser@h-its.org>

RUN apt-get update \
 && apt-get install -y \
    rpm \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
